background                  #181816
foreground                  #b2b1aa
active_tab_foreground       #b2b1aa
active_tab_background       #181816
inactive_tab_foreground     #b2b1aa
inactive_tab_background     #282826
selection_foreground        #b2b1aa
selection_background        #282826

# Black
color0 #282826
color8 #4C4B48

# Red
color1 #DA6561
color9 #DA6561

# Green
color2  #7DA98E
color10 #7DA98E

# Blue
color4  #7A92B2
color12 #7A92B2

# Magenta
color5  #99978E
color13 #99978E

# Yellow
color3  #C39A82
color11 #C3B691

# Cyan
color6  #96ADB6
color14 #96ADB6

# White
color7  #84827B
color15 #AEADA8
