background #FCFCFD
foreground #484B51

active_tab_foreground   #484B51
active_tab_background   #E4E4E2

inactive_tab_foreground #484B51
inactive_tab_background #FDFDFC

selection_foreground    #484B51
selection_background    #E0E0E6

# Black
color0 #484B51
color8 #5E6169

# Red
color1 #905454
color9 #905454

# Green
color2 #477A73
color10 #477A73

# Yellow
color3 #67739B
color11 #67739B

# Blue
color4 #1C2024
color12 #1C2024

# Magenta
color5 #484B51
color13 #484B51

# Cyan
color6 #47547A
color14 #47547A

# White
color7 #BEC0CB
color15 #E6E6EB
