#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# from https://github.com/FelixKratz/dotfiles/tree/master
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# global settings
yabai -m config                                 \
    mouse_follows_focus         off             \
    focus_follows_mouse         off             \
    mouse_modifier              ctrl            \
    mouse_action1               move            \
    mouse_action2               resize          \
    mouse_drop_action           swap            \
    layout                      float           \
    window_gap                  6               \
    top_padding                 2               \
    bottom_padding              2               \
    left_padding                6               \
    right_padding               6               \
    window_origin_display       default         \
    window_placement            second_child    \
    window_zoom_persist         on              \
    window_shadow               on              \
    window_animation_duration   0.0             \
    window_opacity              off              \
    window_opacity_duration     0.15            \
    active_window_opacity       1.0             \
    normal_window_opacity       0.90            

yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0
yabai -m config debug_output on

# find all executable files in ~/.config/yabai and execute them
find "${HOME}/.config/yabai/parts" -type f -perm +111 -exec {} \;
echo "yabai configuration loaded.."
